
database.type: mysql

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wcs_workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&
    username: workflow
    password: Workflow@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    admin:
      username: root
      password: password
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false
    clean-disabled: true
    encoding: UTF-8
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
#    baseline-on-migrate: true

  #flyway.sql-migration-prefix迁移文件的前缀，默认为V.
  #flyway.sql-migration-separator迁移脚本的文件名分隔符，默认__
  #flyway.sql-migration-suffix迁移脚本的后缀，默认为.sql
  #flyway.schemas设定需要flywary迁移的schema，大小写敏感，默认为连接默认的schema.
  #flyway.url迁移时使用的JDBC URL，如果没有指定的话，将使用配置的主数据源
  #flyway.user迁移数据库的用户名
  #flyway.password目标数据库的密码.


camunda.bpm.admin-user:
  id: admin
  password: admin